### ISSUE TITLE
🐛 Button / Image Click Issue

### ISSUE THREAD

**Issue by philsinatra** [vhs25/idm231-vhs25#2]
To resolve the issue you're having with your button/image click functionality, you can convert your buttons to inputs that use an image attribute:

```html
<button class="card" id="aries"> <img src="images/card_back_1.png" > </button>

<!-- becomes -->

<input type="image" class="card" id="aries" src="images/card_back_1.png" />
```

Notice the `type="image"` attribute that is added to the new `input` element. This element will work like a button, but look like an image, and solve your click issue.

Once you change your current setup to use this new input format, you'll adjust your JavaScript and CSS accordingly to keep your click functionality and CSS styles working.

```diff
- const buttons = document.querySelectorAll('button');
+ const buttons = document.querySelectorAll('.card');
```

```diff
- .flip-card-front img {
+ .flip-card-front input[type="image"] {

- .flip-card-front img:hover {
+ .flip-card-front input[type="image"]:hover {
```

Once you make these changes, you have the selected button's `id` which tells you which sign you need to show. Make these updates, then work on your _ice cream_ function that updates the text/images etc in your app based on if the user clicks _aries_ or _gemini_ etc.

**Comment by vhs25** [comment]
It works! Thank you for your help :)
